project_id = "zmlwicrlcuqgxfaskxic"

[functions.send-whatsapp]
verify_jwt = false

[functions.wa-generate-qr]
verify_jwt = true

[functions.wa-device]
verify_jwt = true

[functions.lookup-pendaftar]
verify_jwt = false

[functions.create-donation]
verify_jwt = false

[functions.mayar-webhook]
verify_jwt = false

[functions.recent-donations]
verify_jwt = false

[functions.cek-status-pendaftar]
verify_jwt = false
