import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, CheckCircle2, GraduationCap, HeartHandshake, KeyRound, Loader2, MessageSquareText, ShieldCheck, Trophy } from "lucide-react";
import { toast } from "sonner";
import { AdSlot } from "@/components/ads/AdSlot";
import { supabase } from "@/integrations/supabase/client";
import { saveStudyAccess, studyLabel, studyPrefix, type StudyKind, type VerifiedRegistrant } from "@/lib/study-case";

export const Route = createFileRoute("/studi-kasus")({
  head: () => ({ meta: [{ title: "Validasi Studi Kasus — Kejar Prestasi" }, { name: "description", content: "Validasi kode pendaftaran sebelum mengisi Studi Kasus Kejar Prestasi." }] }),
  component: StudyCaseValidationPage,
});

function StudyCaseValidationPage() {
  const [kind, setKind] = useState<StudyKind | null>(null);
  return <main className="bg-slate-50"><section className="relative overflow-hidden border-b border-border bg-white"><div className="absolute inset-0 opacity-[.18] [background-image:linear-gradient(to_right,color-mix(in_oklab,var(--primary)_8%,transparent)_1px,transparent_1px),linear-gradient(to_bottom,color-mix(in_oklab,var(--primary)_8%,transparent)_1px,transparent_1px)] [background-size:52px_52px]"/><div className="absolute -right-24 -top-28 h-80 w-80 rounded-full bg-primary/10 blur-3xl"/><div className="container-page relative py-12 md:py-16"><Link to="/" className="text-xs font-bold text-primary">← Kembali ke Beranda</Link><div className="mt-7 grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary-soft px-4 py-2 text-xs font-extrabold uppercase tracking-[.18em] text-primary"><MessageSquareText size={15}/> Tahap 3 · Studi Kasus</span><h1 className="mt-5 text-3xl font-black leading-tight text-foreground md:text-5xl">Satu kode untuk membuka ruang jawabanmu.</h1><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">Pilih kategori, verifikasi kode pendaftaran, lalu sistem akan mengarahkanmu ke formulir Studi Kasus yang sesuai.</p></div><div className="hidden gap-2 lg:flex">{["Pilih kategori","Validasi kode","Isi jawaban"].map((item,index)=><div key={item} className="w-28 rounded-2xl border border-border bg-white p-3 shadow-card"><span className="text-xs font-black text-primary">0{index+1}</span><p className="mt-2 text-xs font-bold leading-4 text-foreground">{item}</p></div>)}</div></div></div></section><AdSlot placement="study_validation_top"/><section className="container-page py-10 md:py-14">{kind ? <VerificationGate kind={kind} onBack={() => setKind(null)}/> : <><div className="mb-7 text-center"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-primary">Pilih Kategori</p><h2 className="mt-2 text-2xl font-black">Kategori pendaftaranmu</h2><p className="mt-2 text-sm text-muted-foreground">Pilih sesuai kode pendaftaran yang kamu miliki.</p></div><div className="grid gap-5 md:grid-cols-3"><Choice number="01" kind="prestasi" icon={<Trophy/>} desc="Gunakan kode KP-PRE sesuai pendaftaranmu." onClick={() => setKind("prestasi")}/><Choice number="02" kind="ekonomi" icon={<HeartHandshake/>} desc="Gunakan kode KP-EKO sesuai pendaftaranmu." onClick={() => setKind("ekonomi")}/><Choice number="03" kind="umum" icon={<GraduationCap/>} desc="Gunakan kode KP-UMM sesuai pendaftaranmu." onClick={() => setKind("umum")}/></div></>}</section><AdSlot placement="study_validation_bottom"/></main>;
}

function Choice({ kind, icon, desc, onClick, number }: { kind: StudyKind; icon: React.ReactNode; desc: string; onClick: () => void; number: string }) {
  return <button onClick={onClick} className="group relative block min-h-[360px] overflow-hidden rounded-[2rem] border border-border/80 bg-card p-6 text-left shadow-card transition-all duration-300 hover:-translate-y-1.5 hover:shadow-soft sm:p-8"><span className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-primary to-[oklch(0.55_0.22_290)]"/><span className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-primary/20 opacity-40 blur-3xl transition-all duration-500 group-hover:scale-125"/><div className="relative flex items-start justify-between gap-5"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-primary/15 bg-primary-soft text-primary shadow-card transition-transform group-hover:scale-105">{icon}</div><span className="rounded-full border border-border bg-background/70 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Pilih · {number}</span></div><span className="relative mt-6 inline-block text-xs font-bold uppercase tracking-wider text-primary">Beasiswa {studyLabel(kind)}</span><h2 className="mt-2 text-xl font-bold leading-snug text-foreground sm:text-2xl">Buka Studi Kasus {studyLabel(kind)}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{desc}</p><ul className="relative mt-5 space-y-2 text-sm text-foreground/80"><li className="flex items-start gap-2"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-primary"/>Validasi kode pendaftaran</li><li className="flex items-start gap-2"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-primary"/>Form sesuai kategori</li><li className="flex items-start gap-2"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-primary"/>Akses aman dan terverifikasi</li></ul><div className="relative mt-7 inline-flex items-center gap-2 text-sm font-bold text-primary">Pilih & Validasi <ArrowRight size={16} className="transition-transform group-hover:translate-x-1"/></div></button>;
}

function VerificationGate({ kind, onBack }: { kind: StudyKind; onBack: () => void }) {
  const [token, setToken] = useState(""); const [checking, setChecking] = useState(false); const [error, setError] = useState(""); const prefix = studyPrefix(kind);
  const verify = async () => {
    const normalized = token.trim().toUpperCase(); setError("");
    if (!normalized) return setError("Masukkan kode pendaftaran terlebih dahulu.");
    if (!normalized.startsWith(prefix)) return setError(`Kode tidak sesuai kategori. Gunakan kode yang diawali ${prefix}`);
    setChecking(true);
    try {
      const { data, error: lookupError } = await supabase.functions.invoke("lookup-pendaftar", { body: { token: normalized, kind } });
      if (lookupError || !data?.ok || !data?.data) return setError("Kode pendaftaran tidak valid, tidak ditemukan, atau tidak sesuai kategori.");
      saveStudyAccess(normalized, kind, data.data as VerifiedRegistrant);
      toast.success("Kode valid. Membuka halaman Studi Kasus...");
      window.location.assign("/studi-kasus/form");
    } catch { setError("Validasi gagal. Silakan coba kembali."); } finally { setChecking(false); }
  };
  return <div className="mx-auto grid max-w-4xl overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl md:grid-cols-[.8fr_1.2fr]"><aside className="relative overflow-hidden bg-slate-950 p-7 text-white md:p-9"><div className="absolute -bottom-16 -left-16 h-52 w-52 rounded-full bg-violet-600/30 blur-2xl"/><div className="relative"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500/20 text-violet-300"><KeyRound/></div><p className="mt-8 text-xs font-black uppercase tracking-[.2em] text-violet-300">Access Scanner</p><h2 className="mt-2 text-2xl font-black">Beasiswa {studyLabel(kind)}</h2><p className="mt-3 text-sm leading-6 text-slate-400">Kode diperiksa langsung dan hanya akses yang sesuai kategori yang dapat melanjutkan.</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Awalan kode</p><p className="mt-1 font-mono text-xl font-black text-white">{prefix}</p></div></div></aside><div className="p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-wider text-primary">Validasi Pendaftar</p><h3 className="mt-2 text-2xl font-extrabold">Masukkan kode pendaftaran</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Setelah berhasil, halaman akan dimuat ulang menuju formulir Studi Kasus.</p><label className="mt-7 block text-sm font-bold">Kode Pendaftaran<input value={token} onChange={e => { setToken(e.target.value.toUpperCase()); setError(""); }} onKeyDown={e => { if (e.key === "Enter") { e.preventDefault(); verify(); } }} placeholder={`${prefix}XXXXXX`} className="mt-2 w-full rounded-xl border border-border bg-slate-50 px-4 py-4 font-mono text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10"/></label>{error && <div className="mt-4 rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button type="button" onClick={onBack} className="rounded-xl border border-border px-5 py-3 text-sm font-bold">Ganti kategori</button><button type="button" onClick={verify} disabled={checking} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50">{checking ? <Loader2 size={16} className="animate-spin"/> : <ShieldCheck size={16}/>}Validasi & Buka</button></div></div></div>;
}
