import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, GraduationCap, HeartHandshake, KeyRound, Loader2, MessageSquareText, ShieldCheck, Trophy } from "lucide-react";
import { toast } from "sonner";
import { AdSlot } from "@/components/ads/AdSlot";
import { supabase } from "@/integrations/supabase/client";
import { saveStudyAccess, studyLabel, studyPrefix, type StudyKind, type VerifiedRegistrant } from "@/lib/study-case";

export const Route = createFileRoute("/studi-kasus")({
  head: () => ({ meta: [{ title: "Validasi Studi Kasus — Kejar Prestasi" }, { name: "description", content: "Validasi kode pendaftaran sebelum mengisi Studi Kasus Kejar Prestasi." }] }),
  component: StudyCaseValidationPage,
});

function StudyCaseValidationPage() {
  const [kind, setKind] = useState<StudyKind | null>(null);
  return <main className="bg-slate-50"><section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.16)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.16)_1px,transparent_1px)] [background-size:44px_44px]"/><div className="absolute -right-24 -top-28 h-80 w-80 rounded-full bg-violet-500/30 blur-3xl"/><div className="container-page relative py-12 md:py-20"><Link to="/" className="text-xs font-bold text-violet-300">← Kembali ke Beranda</Link><div className="mt-7 grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-extrabold uppercase tracking-[.18em] text-violet-200"><MessageSquareText size={15}/> Tahap 3 · Studi Kasus</span><h1 className="mt-5 text-3xl font-black leading-tight md:text-5xl">Satu kode untuk membuka ruang jawabanmu.</h1><p className="mt-4 max-w-2xl leading-7 text-slate-300">Pilih kategori, verifikasi kode pendaftaran, lalu sistem akan mengarahkanmu ke formulir Studi Kasus yang sesuai.</p></div><div className="hidden gap-2 lg:flex">{["Pilih kategori","Validasi kode","Isi jawaban"].map((item,index)=><div key={item} className="w-28 rounded-2xl border border-white/10 bg-white/5 p-3"><span className="text-xs font-black text-violet-300">0{index+1}</span><p className="mt-2 text-xs font-bold leading-4">{item}</p></div>)}</div></div></div></section><AdSlot placement="study_validation_top"/><section className="container-page py-10 md:py-14">{kind ? <VerificationGate kind={kind} onBack={() => setKind(null)}/> : <><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-primary">Pilih Access Pass</p><h2 className="mt-2 text-2xl font-black">Kategori pendaftaranmu</h2></div><span className="hidden text-sm text-muted-foreground sm:block">3 kategori tersedia</span></div><div className="grid gap-5 md:grid-cols-3"><Choice number="01" tone="violet" kind="prestasi" icon={<Trophy/>} desc="Gunakan kode KP-PRE sesuai pendaftaranmu." onClick={() => setKind("prestasi")}/><Choice number="02" tone="emerald" kind="ekonomi" icon={<HeartHandshake/>} desc="Gunakan kode KP-EKO sesuai pendaftaranmu." onClick={() => setKind("ekonomi")}/><Choice number="03" tone="amber" kind="umum" icon={<GraduationCap/>} desc="Gunakan kode KP-UMM sesuai pendaftaranmu." onClick={() => setKind("umum")}/></div></>}</section><AdSlot placement="study_validation_bottom"/></main>;
}

function Choice({ kind, icon, desc, onClick, number, tone }: { kind: StudyKind; icon: React.ReactNode; desc: string; onClick: () => void; number: string; tone: "violet" | "emerald" | "amber" }) {
  const styles = { violet: "from-violet-700 to-indigo-950 text-violet-100", emerald: "from-emerald-600 to-teal-950 text-emerald-100", amber: "from-amber-500 to-orange-900 text-amber-50" }[tone];
  return <button onClick={onClick} className={`group relative min-h-72 overflow-hidden rounded-[1.75rem] bg-gradient-to-br p-6 text-left text-white shadow-lg transition duration-300 hover:-translate-y-1.5 hover:shadow-2xl ${styles}`}><div className="absolute -right-14 -top-14 h-40 w-40 rounded-full border border-white/15"/><div className="absolute -right-5 top-10 h-28 w-28 rounded-full border border-white/10"/><div className="relative flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl border border-white/20 bg-white/15 shadow-inner backdrop-blur">{icon}</div><span className="font-mono text-sm font-black tracking-widest opacity-70">{number}</span></div><div className="relative mt-12"><span className="text-[10px] font-extrabold uppercase tracking-[.2em] opacity-70">Study Access Pass</span><h2 className="mt-2 text-2xl font-black">Beasiswa {studyLabel(kind)}</h2><p className="mt-3 max-w-xs text-sm leading-6 opacity-80">{desc}</p><span className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-extrabold text-slate-900 transition group-hover:gap-3">Pilih kategori <ArrowRight size={15}/></span></div></button>;
}

function VerificationGate({ kind, onBack }: { kind: StudyKind; onBack: () => void }) {
  const [token, setToken] = useState(""); const [checking, setChecking] = useState(false); const [error, setError] = useState(""); const prefix = studyPrefix(kind);
  const verify = async () => {
    const normalized = token.trim().toUpperCase(); setError("");
    if (!normalized) return setError("Masukkan kode pendaftaran terlebih dahulu.");
    if (!normalized.startsWith(prefix)) return setError(`Kode tidak sesuai kategori. Gunakan kode yang diawali ${prefix}`);
    setChecking(true);
    try {
      const { data, error: lookupError } = await supabase.functions.invoke("lookup-pendaftar", { body: { token: normalized, kind } });
      if (lookupError || !data?.ok || !data?.data) return setError("Kode pendaftaran tidak valid, tidak ditemukan, atau tidak sesuai kategori.");
      saveStudyAccess(normalized, kind, data.data as VerifiedRegistrant);
      toast.success("Kode valid. Membuka halaman Studi Kasus...");
      window.location.assign("/studi-kasus/form");
    } catch { setError("Validasi gagal. Silakan coba kembali."); } finally { setChecking(false); }
  };
  return <div className="mx-auto grid max-w-4xl overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl md:grid-cols-[.8fr_1.2fr]"><aside className="relative overflow-hidden bg-slate-950 p-7 text-white md:p-9"><div className="absolute -bottom-16 -left-16 h-52 w-52 rounded-full bg-violet-600/30 blur-2xl"/><div className="relative"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500/20 text-violet-300"><KeyRound/></div><p className="mt-8 text-xs font-black uppercase tracking-[.2em] text-violet-300">Access Scanner</p><h2 className="mt-2 text-2xl font-black">Beasiswa {studyLabel(kind)}</h2><p className="mt-3 text-sm leading-6 text-slate-400">Kode diperiksa langsung dan hanya akses yang sesuai kategori yang dapat melanjutkan.</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Awalan kode</p><p className="mt-1 font-mono text-xl font-black text-white">{prefix}</p></div></div></aside><div className="p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-wider text-primary">Validasi Pendaftar</p><h3 className="mt-2 text-2xl font-extrabold">Masukkan kode pendaftaran</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Setelah berhasil, halaman akan dimuat ulang menuju formulir Studi Kasus.</p><label className="mt-7 block text-sm font-bold">Kode Pendaftaran<input value={token} onChange={e => { setToken(e.target.value.toUpperCase()); setError(""); }} onKeyDown={e => { if (e.key === "Enter") { e.preventDefault(); verify(); } }} placeholder={`${prefix}XXXXXX`} className="mt-2 w-full rounded-xl border border-border bg-slate-50 px-4 py-4 font-mono text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10"/></label>{error && <div className="mt-4 rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button type="button" onClick={onBack} className="rounded-xl border border-border px-5 py-3 text-sm font-bold">Ganti kategori</button><button type="button" onClick={verify} disabled={checking} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50">{checking ? <Loader2 size={16} className="animate-spin"/> : <ShieldCheck size={16}/>}Validasi & Buka</button></div></div></div>;
}
