import { useState } from "react";
import { Link,useNavigate,useSearch } from "@tanstack/react-router";
import { ArrowRight,CheckCircle2,Loader2,ShieldCheck,UserRound,Mail,Phone,MapPin,GraduationCap,CalendarDays,School,VenetianMask } from "lucide-react";
import { toast } from "sonner";
import { submitRegistrationFn,sendAppEmail } from "@/lib/api";
import { supabase } from "@/integrations/supabase/client";
import { AdSlot } from "@/components/ads/AdSlot";
type Kind="prestasi"|"ekonomi";type Jalur="reguler"|"akselerasi"|"platinum";type FormState={full_name:string;birth_place:string;birth_date:string;gender:string;address:string;whatsapp:string;email:string;education_level:string;school_name:string;grade:string};const initial:FormState={full_name:"",birth_place:"",birth_date:"",gender:"",address:"",whatsapp:"",email:"",education_level:"",school_name:"",grade:""};
export function RegistrationForm({kind}:{kind:Kind}){const navigate=useNavigate();const search=useSearch({strict:false}) as{jalur?:string};const jalur:Jalur=search.jalur==="akselerasi"||search.jalur==="platinum"?search.jalur:"reguler";const[form,setForm]=useState<FormState>(initial),[submitting,setSubmitting]=useState(false);const isPrestasi=kind==="prestasi",jalurLabel=jalur==="platinum"?"Akselerasi Platinum":jalur==="akselerasi"?"Akselerasi":"Reguler";const set=(k:keyof FormState,v:string)=>setForm(s=>({...s,[k]:v}));const submit=async(e:React.FormEvent)=>{e.preventDefault();if(Object.values(form).some(v=>!v.trim()))return toast.error("Lengkapi seluruh data identitas terlebih dahulu");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))return toast.error("Email tidak valid");if(!/^[+\d\s-]{8,25}$/.test(form.whatsapp))return toast.error("Nomor WhatsApp tidak valid");setSubmitting(true);try{const payload={...form,kind,status:jalur==="reguler"?"pending":"approved",extra:{jalur_pendaftaran:jalur}};const{token}=await submitRegistrationFn({data:payload as never});supabase.functions.invoke("send-whatsapp",{body:{type:"pendaftaran",full_name:form.full_name,email:form.email,whatsapp:form.whatsapp,kind,token}}).catch(()=>{});sendAppEmail({data:{templateName:"registration-confirmation",recipientEmail:form.email,idempotencyKey:`reg-${token}`,templateData:{fullName:form.full_name,token,kind,whatsapp:form.whatsapp}}}).catch(()=>{});if(jalur!=="reguler"){const{data:pay,error:payErr}=await supabase.functions.invoke("create-registration-payment",{body:{token}});if(payErr||!pay?.ok)throw new Error(pay?.error||"Gagal membuat pembayaran Mayar");if(pay.status==="paid"){navigate({to:"/pendaftaran/sukses",search:{name:form.full_name,email:form.email,whatsapp:form.whatsapp,kind,token}});return}if(pay.link){toast.success("Pendaftaran tersimpan. Lanjutkan pembayaran Mayar.");window.location.href=pay.link;return}throw new Error("Link pembayaran tidak tersedia")};toast.success("Pendaftaran berhasil dikirim");navigate({to:"/pendaftaran/sukses",search:{name:form.full_name,email:form.email,whatsapp:form.whatsapp,kind,token}})}catch(err){console.error(err);toast.error(err instanceof Error?err.message:"Pendaftaran gagal dikirim. Silakan coba kembali.")}finally{setSubmitting(false)}};return <>
<section className="relative overflow-hidden border-b border-border bg-background"><div className="absolute inset-x-0 top-0 h-52 bg-primary/8 blur-3xl"/><div className="container-page relative py-10 md:py-14"><Link to={isPrestasi?"/beasiswa-prestasi":"/beasiswa-ekonomi"} className="text-xs font-semibold text-primary">← Kembali ke halaman beasiswa</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px] lg:items-stretch"><div className="rounded-[2rem] border border-border bg-card p-6 shadow-card md:p-8"><span className="inline-flex rounded-full bg-primary-soft px-3 py-1 text-[10px] font-black uppercase tracking-wider text-primary">Formulir Pendaftaran</span><h1 className="mt-4 text-3xl font-extrabold md:text-4xl">Isi Identitas Pendaftar</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground md:text-base">Isi data dasar terlebih dahulu. Informasi prestasi, ekonomi, dan dokumen pendukung akan dilengkapi pada tahap berikutnya.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><MiniStat label="Kategori" value={isPrestasi?"Prestasi":"Ekonomi"}/><MiniStat label="Jalur" value={jalurLabel}/><MiniStat label="Tahap" value="Identitas"/></div></div><div className={`rounded-[2rem] border p-6 shadow-card ${jalur==="platinum"?"border-emerald-200 bg-emerald-50/70":jalur==="akselerasi"?"border-amber-200 bg-amber-50/70":"border-primary/15 bg-primary-soft/60"}`}><p className="text-[10px] font-black uppercase tracking-[.14em] text-muted-foreground">Jalur dipilih</p><p className="mt-2 text-2xl font-black text-foreground">{jalurLabel}</p><p className="mt-1 text-sm text-muted-foreground">{jalur==="reguler"?"Gratis tanpa biaya pendaftaran":jalur==="akselerasi"?"\n":"Rp45.000 · pembayaran via Mayar"}</p><div className="mt-5 flex items-center gap-2 rounded-xl bg-background/80 px-3.5 py-3 text-xs font-semibold text-foreground"><ShieldCheck size={15} className="text-primary"/>Data diproses melalui sistem resmi Kejar Prestasi.</div></div></div></div></section>
<AdSlot placement="form_top"/>
<section className="container-page py-10 md:py-14"><form onSubmit={submit} className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="rounded-[2rem] border border-border bg-card p-5 shadow-card sm:p-7"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary-soft text-primary"><UserRound size={21}/></div><div><p className="text-[10px] font-black uppercase tracking-widest text-primary">Data utama</p><h2 className="mt-0.5 text-xl font-extrabold">Identitas Pendaftar</h2><p className="mt-1 text-xs text-muted-foreground">Gunakan data aktif dan sesuai identitas.</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2">
<Field icon={<UserRound size={16}/>} label="Nama Lengkap" placeholder="Contoh: Rizky Pratama" value={form.full_name} onChange={v=>set("full_name",v)}/>
<Field icon={<MapPin size={16}/>} label="Tempat Lahir" placeholder="Contoh: Purwokerto" value={form.birth_place} onChange={v=>set("birth_place",v)}/>
<Field icon={<CalendarDays size={16}/>} label="Tanggal Lahir" type="date" value={form.birth_date} onChange={v=>set("birth_date",v)}/>
<Select icon={<VenetianMask size={16}/>} label="Jenis Kelamin" placeholder="Pilih jenis kelamin" value={form.gender} onChange={v=>set("gender",v)} options={["Laki-laki","Perempuan"]}/>
<Field icon={<Phone size={16}/>} label="Nomor WhatsApp Aktif" type="tel" placeholder="Contoh: 081234567890" value={form.whatsapp} onChange={v=>set("whatsapp",v)}/>
<Field icon={<Mail size={16}/>} label="Email Aktif" type="email" placeholder="Contoh: nama@email.com" value={form.email} onChange={v=>set("email",v)}/>
<Select icon={<GraduationCap size={16}/>} label="Jenjang Pendidikan" placeholder="Pilih jenjang pendidikan" value={form.education_level} onChange={v=>set("education_level",v)} options={["SD/MI","SMP/MTs","SMA/SMK/MA","D3","D4/S1","S2"]}/>
<Field icon={<School size={16}/>} label="Sekolah / Kampus" placeholder="Contoh: SMA Negeri 1 / Universitas Indonesia" value={form.school_name} onChange={v=>set("school_name",v)}/>
<Field icon={<GraduationCap size={16}/>} label="Kelas / Semester" placeholder="Contoh: XII IPA 1 / Semester 4" value={form.grade} onChange={v=>set("grade",v)}/>
<label className="sm:col-span-2"><span className="flex items-center gap-2 text-xs font-semibold"><MapPin size={15} className="text-primary"/>Alamat Domisili</span><textarea required value={form.address} onChange={e=>set("address",e.target.value)} rows={4} className="mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3.5 text-sm outline-none transition placeholder:text-muted-foreground/55 focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="Contoh: Jl. Pendidikan No. 10, Kecamatan ..., Kabupaten/Kota ..., Provinsi ..."/></label>
</div></div><aside className="h-fit rounded-[2rem] border border-border bg-card p-6 shadow-card lg:sticky lg:top-24"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-primary-soft text-primary"><ShieldCheck size={19}/></div><h3 className="mt-4 text-lg font-extrabold">Setelah pendaftaran</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">Tahapan berikutnya akan aktif setelah formulir ini berhasil dikirim.</p><div className="mt-5 grid gap-3">{[jalur==="reguler"?"Tidak ada pembayaran pendaftaran":"Selesaikan pembayaran Mayar terlebih dahulu","Simpan kode pendaftar dari sistem","Lanjutkan Bagikan Program & Studi Kasus","Pantau progres di Portal Pendaftar"].map((t,i)=><div key={t} className="flex items-start gap-3 rounded-xl border border-border/70 bg-secondary/20 px-3.5 py-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-primary text-[10px] font-black text-primary-foreground">{i+1}</span><p className="text-sm leading-5 text-foreground/80">{t}</p></div>)}</div>{jalur!=="reguler"&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Pembayaran divalidasi otomatis.</b><p className="mt-1 text-xs leading-5">Kode Pendaftaran akan diberikan setelah pembayaran berhasil.</p></div>}<button disabled={submitting} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3.5 text-sm font-black text-primary-foreground shadow-soft transition hover:-translate-y-0.5 disabled:opacity-50">{submitting?<Loader2 size={16} className="animate-spin"/>:<ArrowRight size={16}/>} {jalur==="reguler"?"Kirim Pendaftaran":"Daftar & Lanjut Pembayaran"}</button></aside></form></section></>}
function MiniStat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-border bg-secondary/20 px-4 py-3"><p className="text-[9px] font-black uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>}
function Field({label,value,onChange,type="text",placeholder="",icon}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string;icon?:React.ReactNode}){return <label><span className="flex items-center gap-2 text-xs font-semibold">{icon&&<span className="text-primary">{icon}</span>}{label}</span><input required type={type} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3.5 text-sm outline-none transition placeholder:text-muted-foreground/55 focus:border-primary focus:ring-4 focus:ring-primary/10"/></label>}
function Select({label,value,onChange,options,placeholder="Pilih",icon}:{label:string;value:string;onChange:(v:string)=>void;options:string[];placeholder?:string;icon?:React.ReactNode}){return <label><span className="flex items-center gap-2 text-xs font-semibold">{icon&&<span className="text-primary">{icon}</span>}{label}</span><select required value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3.5 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"><option value="">{placeholder}</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
