/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as CekStatusRouteImport } from './routes/cek-status'
import { Route as BeasiswaPrestasiRouteImport } from './routes/beasiswa-prestasi'
import { Route as BeasiswaEkonomiRouteImport } from './routes/beasiswa-ekonomi'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BerkasIndexRouteImport } from './routes/berkas.index'
import { Route as BagikanPosterIndexRouteImport } from './routes/bagikan-poster.index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PendaftaranSuksesRouteImport } from './routes/pendaftaran.sukses'
import { Route as PendaftaranPrestasiRouteImport } from './routes/pendaftaran.prestasi'
import { Route as PendaftaranEkonomiRouteImport } from './routes/pendaftaran.ekonomi'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DonasiTerimaKasihRouteImport } from './routes/donasi.terima-kasih'
import { Route as BerkasTerkirimRouteImport } from './routes/berkas.terkirim'
import { Route as BerkasPrestasiRouteImport } from './routes/berkas.prestasi'
import { Route as BerkasEkonomiRouteImport } from './routes/berkas.ekonomi'
import { Route as BagikanPosterPrestasiRouteImport } from './routes/bagikan-poster.prestasi'
import { Route as BagikanPosterEkonomiRouteImport } from './routes/bagikan-poster.ekonomi'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminSistemUpdateRouteImport } from './routes/admin.sistem-update'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminPendaftarRouteImport } from './routes/admin.pendaftar'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminKodeKustomRouteImport } from './routes/admin.kode-kustom'
import { Route as AdminKeamananRouteImport } from './routes/admin.keamanan'
import { Route as AdminKandidatRouteImport } from './routes/admin.kandidat'
import { Route as AdminIklanKustomRouteImport } from './routes/admin.iklan-kustom'
import { Route as AdminFormulirRouteImport } from './routes/admin.formulir'
import { Route as AdminEmailTemplateRouteImport } from './routes/admin.email-template'
import { Route as AdminDonasiRouteImport } from './routes/admin.donasi'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminBerkasRouteImport } from './routes/admin.berkas'
import { Route as AdminBagikanPosterRouteImport } from './routes/admin.bagikan-poster'
import { Route as AdminArtikelRouteImport } from './routes/admin.artikel'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiBalasanRouteImport } from './routes/admin.ai-balasan'
import { Route as AdminAdsenseRouteImport } from './routes/admin.adsense'
import { Route as BerkasPrestasiIndexRouteImport } from './routes/berkas.prestasi.index'
import { Route as BerkasEkonomiIndexRouteImport } from './routes/berkas.ekonomi.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as BerkasPrestasiUploadRouteImport } from './routes/berkas.prestasi.upload'
import { Route as BerkasEkonomiUploadRouteImport } from './routes/berkas.ekonomi.upload'
import { Route as ApiPublicWaWebhookRouteImport } from './routes/api/public/wa-webhook'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicGithubWebhookRouteImport } from './routes/api/public/github-webhook'
import { Route as AdminInstalasiVpsRouteImport } from './routes/admin.instalasi.vps'
import { Route as AdminInstalasiHostingRouteImport } from './routes/admin.instalasi.hosting'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const CekStatusRoute = CekStatusRouteImport.update({
  id: '/cek-status',
  path: '/cek-status',
  getParentRoute: () => rootRouteImport,
} as any)
const BeasiswaPrestasiRoute = BeasiswaPrestasiRouteImport.update({
  id: '/beasiswa-prestasi',
  path: '/beasiswa-prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BeasiswaEkonomiRoute = BeasiswaEkonomiRouteImport.update({
  id: '/beasiswa-ekonomi',
  path: '/beasiswa-ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasIndexRoute = BerkasIndexRouteImport.update({
  id: '/berkas/',
  path: '/berkas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagikanPosterIndexRoute = BagikanPosterIndexRouteImport.update({
  id: '/bagikan-poster/',
  path: '/bagikan-poster/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PendaftaranSuksesRoute = PendaftaranSuksesRouteImport.update({
  id: '/pendaftaran/sukses',
  path: '/pendaftaran/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranPrestasiRoute = PendaftaranPrestasiRouteImport.update({
  id: '/pendaftaran/prestasi',
  path: '/pendaftaran/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranEkonomiRoute = PendaftaranEkonomiRouteImport.update({
  id: '/pendaftaran/ekonomi',
  path: '/pendaftaran/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiTerimaKasihRoute = DonasiTerimaKasihRouteImport.update({
  id: '/donasi/terima-kasih',
  path: '/donasi/terima-kasih',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasTerkirimRoute = BerkasTerkirimRouteImport.update({
  id: '/berkas/terkirim',
  path: '/berkas/terkirim',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasPrestasiRoute = BerkasPrestasiRouteImport.update({
  id: '/berkas/prestasi',
  path: '/berkas/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasEkonomiRoute = BerkasEkonomiRouteImport.update({
  id: '/berkas/ekonomi',
  path: '/berkas/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const BagikanPosterPrestasiRoute = BagikanPosterPrestasiRouteImport.update({
  id: '/bagikan-poster/prestasi',
  path: '/bagikan-poster/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BagikanPosterEkonomiRoute = BagikanPosterEkonomiRouteImport.update({
  id: '/bagikan-poster/ekonomi',
  path: '/bagikan-poster/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSistemUpdateRoute = AdminSistemUpdateRouteImport.update({
  id: '/sistem-update',
  path: '/sistem-update',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendaftarRoute = AdminPendaftarRouteImport.update({
  id: '/pendaftar',
  path: '/pendaftar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKodeKustomRoute = AdminKodeKustomRouteImport.update({
  id: '/kode-kustom',
  path: '/kode-kustom',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeamananRoute = AdminKeamananRouteImport.update({
  id: '/keamanan',
  path: '/keamanan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKandidatRoute = AdminKandidatRouteImport.update({
  id: '/kandidat',
  path: '/kandidat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIklanKustomRoute = AdminIklanKustomRouteImport.update({
  id: '/iklan-kustom',
  path: '/iklan-kustom',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormulirRoute = AdminFormulirRouteImport.update({
  id: '/formulir',
  path: '/formulir',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplateRoute = AdminEmailTemplateRouteImport.update({
  id: '/email-template',
  path: '/email-template',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonasiRoute = AdminDonasiRouteImport.update({
  id: '/donasi',
  path: '/donasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBerkasRoute = AdminBerkasRouteImport.update({
  id: '/berkas',
  path: '/berkas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBagikanPosterRoute = AdminBagikanPosterRouteImport.update({
  id: '/bagikan-poster',
  path: '/bagikan-poster',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtikelRoute = AdminArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiBalasanRoute = AdminAiBalasanRouteImport.update({
  id: '/ai-balasan',
  path: '/ai-balasan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsenseRoute = AdminAdsenseRouteImport.update({
  id: '/adsense',
  path: '/adsense',
  getParentRoute: () => AdminRoute,
} as any)
const BerkasPrestasiIndexRoute = BerkasPrestasiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BerkasPrestasiRoute,
} as any)
const BerkasEkonomiIndexRoute = BerkasEkonomiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BerkasEkonomiRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasPrestasiUploadRoute = BerkasPrestasiUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => BerkasPrestasiRoute,
} as any)
const BerkasEkonomiUploadRoute = BerkasEkonomiUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => BerkasEkonomiRoute,
} as any)
const ApiPublicWaWebhookRoute = ApiPublicWaWebhookRouteImport.update({
  id: '/api/public/wa-webhook',
  path: '/api/public/wa-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGithubWebhookRoute = ApiPublicGithubWebhookRouteImport.update({
  id: '/api/public/github-webhook',
  path: '/api/public/github-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstalasiVpsRoute = AdminInstalasiVpsRouteImport.update({
  id: '/instalasi/vps',
  path: '/instalasi/vps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstalasiHostingRoute = AdminInstalasiHostingRouteImport.update({
  id: '/instalasi/hosting',
  path: '/instalasi/hosting',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads.txt': typeof AdsDottxtRoute
  '/beasiswa-ekonomi': typeof BeasiswaEkonomiRoute
  '/beasiswa-prestasi': typeof BeasiswaPrestasiRoute
  '/cek-status': typeof CekStatusRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/admin/adsense': typeof AdminAdsenseRoute
  '/admin/ai-balasan': typeof AdminAiBalasanRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/bagikan-poster': typeof AdminBagikanPosterRoute
  '/admin/berkas': typeof AdminBerkasRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/donasi': typeof AdminDonasiRoute
  '/admin/email-template': typeof AdminEmailTemplateRoute
  '/admin/formulir': typeof AdminFormulirRoute
  '/admin/iklan-kustom': typeof AdminIklanKustomRoute
  '/admin/kandidat': typeof AdminKandidatRoute
  '/admin/keamanan': typeof AdminKeamananRoute
  '/admin/kode-kustom': typeof AdminKodeKustomRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/sistem-update': typeof AdminSistemUpdateRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/bagikan-poster/ekonomi': typeof BagikanPosterEkonomiRoute
  '/bagikan-poster/prestasi': typeof BagikanPosterPrestasiRoute
  '/berkas/ekonomi': typeof BerkasEkonomiRouteWithChildren
  '/berkas/prestasi': typeof BerkasPrestasiRouteWithChildren
  '/berkas/terkirim': typeof BerkasTerkirimRoute
  '/donasi/terima-kasih': typeof DonasiTerimaKasihRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pendaftaran/ekonomi': typeof PendaftaranEkonomiRoute
  '/pendaftaran/prestasi': typeof PendaftaranPrestasiRoute
  '/pendaftaran/sukses': typeof PendaftaranSuksesRoute
  '/admin/': typeof AdminIndexRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/bagikan-poster/': typeof BagikanPosterIndexRoute
  '/berkas/': typeof BerkasIndexRoute
  '/admin/instalasi/hosting': typeof AdminInstalasiHostingRoute
  '/admin/instalasi/vps': typeof AdminInstalasiVpsRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/berkas/ekonomi/upload': typeof BerkasEkonomiUploadRoute
  '/berkas/prestasi/upload': typeof BerkasPrestasiUploadRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/berkas/ekonomi/': typeof BerkasEkonomiIndexRoute
  '/berkas/prestasi/': typeof BerkasPrestasiIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/beasiswa-ekonomi': typeof BeasiswaEkonomiRoute
  '/beasiswa-prestasi': typeof BeasiswaPrestasiRoute
  '/cek-status': typeof CekStatusRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/admin/adsense': typeof AdminAdsenseRoute
  '/admin/ai-balasan': typeof AdminAiBalasanRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/bagikan-poster': typeof AdminBagikanPosterRoute
  '/admin/berkas': typeof AdminBerkasRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/donasi': typeof AdminDonasiRoute
  '/admin/email-template': typeof AdminEmailTemplateRoute
  '/admin/formulir': typeof AdminFormulirRoute
  '/admin/iklan-kustom': typeof AdminIklanKustomRoute
  '/admin/kandidat': typeof AdminKandidatRoute
  '/admin/keamanan': typeof AdminKeamananRoute
  '/admin/kode-kustom': typeof AdminKodeKustomRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/sistem-update': typeof AdminSistemUpdateRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/bagikan-poster/ekonomi': typeof BagikanPosterEkonomiRoute
  '/bagikan-poster/prestasi': typeof BagikanPosterPrestasiRoute
  '/berkas/terkirim': typeof BerkasTerkirimRoute
  '/donasi/terima-kasih': typeof DonasiTerimaKasihRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pendaftaran/ekonomi': typeof PendaftaranEkonomiRoute
  '/pendaftaran/prestasi': typeof PendaftaranPrestasiRoute
  '/pendaftaran/sukses': typeof PendaftaranSuksesRoute
  '/admin': typeof AdminIndexRoute
  '/artikel': typeof ArtikelIndexRoute
  '/bagikan-poster': typeof BagikanPosterIndexRoute
  '/berkas': typeof BerkasIndexRoute
  '/admin/instalasi/hosting': typeof AdminInstalasiHostingRoute
  '/admin/instalasi/vps': typeof AdminInstalasiVpsRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/berkas/ekonomi/upload': typeof BerkasEkonomiUploadRoute
  '/berkas/prestasi/upload': typeof BerkasPrestasiUploadRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/berkas/ekonomi': typeof BerkasEkonomiIndexRoute
  '/berkas/prestasi': typeof BerkasPrestasiIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads.txt': typeof AdsDottxtRoute
  '/beasiswa-ekonomi': typeof BeasiswaEkonomiRoute
  '/beasiswa-prestasi': typeof BeasiswaPrestasiRoute
  '/cek-status': typeof CekStatusRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/admin/adsense': typeof AdminAdsenseRoute
  '/admin/ai-balasan': typeof AdminAiBalasanRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/bagikan-poster': typeof AdminBagikanPosterRoute
  '/admin/berkas': typeof AdminBerkasRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/donasi': typeof AdminDonasiRoute
  '/admin/email-template': typeof AdminEmailTemplateRoute
  '/admin/formulir': typeof AdminFormulirRoute
  '/admin/iklan-kustom': typeof AdminIklanKustomRoute
  '/admin/kandidat': typeof AdminKandidatRoute
  '/admin/keamanan': typeof AdminKeamananRoute
  '/admin/kode-kustom': typeof AdminKodeKustomRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/sistem-update': typeof AdminSistemUpdateRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/bagikan-poster/ekonomi': typeof BagikanPosterEkonomiRoute
  '/bagikan-poster/prestasi': typeof BagikanPosterPrestasiRoute
  '/berkas/ekonomi': typeof BerkasEkonomiRouteWithChildren
  '/berkas/prestasi': typeof BerkasPrestasiRouteWithChildren
  '/berkas/terkirim': typeof BerkasTerkirimRoute
  '/donasi/terima-kasih': typeof DonasiTerimaKasihRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/pendaftaran/ekonomi': typeof PendaftaranEkonomiRoute
  '/pendaftaran/prestasi': typeof PendaftaranPrestasiRoute
  '/pendaftaran/sukses': typeof PendaftaranSuksesRoute
  '/admin/': typeof AdminIndexRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/bagikan-poster/': typeof BagikanPosterIndexRoute
  '/berkas/': typeof BerkasIndexRoute
  '/admin/instalasi/hosting': typeof AdminInstalasiHostingRoute
  '/admin/instalasi/vps': typeof AdminInstalasiVpsRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/berkas/ekonomi/upload': typeof BerkasEkonomiUploadRoute
  '/berkas/prestasi/upload': typeof BerkasPrestasiUploadRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/berkas/ekonomi/': typeof BerkasEkonomiIndexRoute
  '/berkas/prestasi/': typeof BerkasPrestasiIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ads.txt'
    | '/beasiswa-ekonomi'
    | '/beasiswa-prestasi'
    | '/cek-status'
    | '/daftar'
    | '/login'
    | '/tentang'
    | '/admin/adsense'
    | '/admin/ai-balasan'
    | '/admin/analytics'
    | '/admin/artikel'
    | '/admin/bagikan-poster'
    | '/admin/berkas'
    | '/admin/branding'
    | '/admin/donasi'
    | '/admin/email-template'
    | '/admin/formulir'
    | '/admin/iklan-kustom'
    | '/admin/kandidat'
    | '/admin/keamanan'
    | '/admin/kode-kustom'
    | '/admin/media'
    | '/admin/pendaftar'
    | '/admin/pengaturan'
    | '/admin/sistem-update'
    | '/admin/whatsapp'
    | '/artikel/$slug'
    | '/bagikan-poster/ekonomi'
    | '/bagikan-poster/prestasi'
    | '/berkas/ekonomi'
    | '/berkas/prestasi'
    | '/berkas/terkirim'
    | '/donasi/terima-kasih'
    | '/email/unsubscribe'
    | '/pendaftaran/ekonomi'
    | '/pendaftaran/prestasi'
    | '/pendaftaran/sukses'
    | '/admin/'
    | '/artikel/'
    | '/bagikan-poster/'
    | '/berkas/'
    | '/admin/instalasi/hosting'
    | '/admin/instalasi/vps'
    | '/api/public/github-webhook'
    | '/api/public/health'
    | '/api/public/wa-webhook'
    | '/berkas/ekonomi/upload'
    | '/berkas/prestasi/upload'
    | '/lovable/email/suppression'
    | '/berkas/ekonomi/'
    | '/berkas/prestasi/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads.txt'
    | '/beasiswa-ekonomi'
    | '/beasiswa-prestasi'
    | '/cek-status'
    | '/daftar'
    | '/login'
    | '/tentang'
    | '/admin/adsense'
    | '/admin/ai-balasan'
    | '/admin/analytics'
    | '/admin/artikel'
    | '/admin/bagikan-poster'
    | '/admin/berkas'
    | '/admin/branding'
    | '/admin/donasi'
    | '/admin/email-template'
    | '/admin/formulir'
    | '/admin/iklan-kustom'
    | '/admin/kandidat'
    | '/admin/keamanan'
    | '/admin/kode-kustom'
    | '/admin/media'
    | '/admin/pendaftar'
    | '/admin/pengaturan'
    | '/admin/sistem-update'
    | '/admin/whatsapp'
    | '/artikel/$slug'
    | '/bagikan-poster/ekonomi'
    | '/bagikan-poster/prestasi'
    | '/berkas/terkirim'
    | '/donasi/terima-kasih'
    | '/email/unsubscribe'
    | '/pendaftaran/ekonomi'
    | '/pendaftaran/prestasi'
    | '/pendaftaran/sukses'
    | '/admin'
    | '/artikel'
    | '/bagikan-poster'
    | '/berkas'
    | '/admin/instalasi/hosting'
    | '/admin/instalasi/vps'
    | '/api/public/github-webhook'
    | '/api/public/health'
    | '/api/public/wa-webhook'
    | '/berkas/ekonomi/upload'
    | '/berkas/prestasi/upload'
    | '/lovable/email/suppression'
    | '/berkas/ekonomi'
    | '/berkas/prestasi'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ads.txt'
    | '/beasiswa-ekonomi'
    | '/beasiswa-prestasi'
    | '/cek-status'
    | '/daftar'
    | '/login'
    | '/tentang'
    | '/admin/adsense'
    | '/admin/ai-balasan'
    | '/admin/analytics'
    | '/admin/artikel'
    | '/admin/bagikan-poster'
    | '/admin/berkas'
    | '/admin/branding'
    | '/admin/donasi'
    | '/admin/email-template'
    | '/admin/formulir'
    | '/admin/iklan-kustom'
    | '/admin/kandidat'
    | '/admin/keamanan'
    | '/admin/kode-kustom'
    | '/admin/media'
    | '/admin/pendaftar'
    | '/admin/pengaturan'
    | '/admin/sistem-update'
    | '/admin/whatsapp'
    | '/artikel/$slug'
    | '/bagikan-poster/ekonomi'
    | '/bagikan-poster/prestasi'
    | '/berkas/ekonomi'
    | '/berkas/prestasi'
    | '/berkas/terkirim'
    | '/donasi/terima-kasih'
    | '/email/unsubscribe'
    | '/pendaftaran/ekonomi'
    | '/pendaftaran/prestasi'
    | '/pendaftaran/sukses'
    | '/admin/'
    | '/artikel/'
    | '/bagikan-poster/'
    | '/berkas/'
    | '/admin/instalasi/hosting'
    | '/admin/instalasi/vps'
    | '/api/public/github-webhook'
    | '/api/public/health'
    | '/api/public/wa-webhook'
    | '/berkas/ekonomi/upload'
    | '/berkas/prestasi/upload'
    | '/lovable/email/suppression'
    | '/berkas/ekonomi/'
    | '/berkas/prestasi/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdsDottxtRoute: typeof AdsDottxtRoute
  BeasiswaEkonomiRoute: typeof BeasiswaEkonomiRoute
  BeasiswaPrestasiRoute: typeof BeasiswaPrestasiRoute
  CekStatusRoute: typeof CekStatusRoute
  DaftarRoute: typeof DaftarRoute
  LoginRoute: typeof LoginRoute
  TentangRoute: typeof TentangRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  BagikanPosterEkonomiRoute: typeof BagikanPosterEkonomiRoute
  BagikanPosterPrestasiRoute: typeof BagikanPosterPrestasiRoute
  BerkasEkonomiRoute: typeof BerkasEkonomiRouteWithChildren
  BerkasPrestasiRoute: typeof BerkasPrestasiRouteWithChildren
  BerkasTerkirimRoute: typeof BerkasTerkirimRoute
  DonasiTerimaKasihRoute: typeof DonasiTerimaKasihRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PendaftaranEkonomiRoute: typeof PendaftaranEkonomiRoute
  PendaftaranPrestasiRoute: typeof PendaftaranPrestasiRoute
  PendaftaranSuksesRoute: typeof PendaftaranSuksesRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
  BagikanPosterIndexRoute: typeof BagikanPosterIndexRoute
  BerkasIndexRoute: typeof BerkasIndexRoute
  ApiPublicGithubWebhookRoute: typeof ApiPublicGithubWebhookRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicWaWebhookRoute: typeof ApiPublicWaWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-status': {
      id: '/cek-status'
      path: '/cek-status'
      fullPath: '/cek-status'
      preLoaderRoute: typeof CekStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beasiswa-prestasi': {
      id: '/beasiswa-prestasi'
      path: '/beasiswa-prestasi'
      fullPath: '/beasiswa-prestasi'
      preLoaderRoute: typeof BeasiswaPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beasiswa-ekonomi': {
      id: '/beasiswa-ekonomi'
      path: '/beasiswa-ekonomi'
      fullPath: '/beasiswa-ekonomi'
      preLoaderRoute: typeof BeasiswaEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/': {
      id: '/berkas/'
      path: '/berkas'
      fullPath: '/berkas/'
      preLoaderRoute: typeof BerkasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagikan-poster/': {
      id: '/bagikan-poster/'
      path: '/bagikan-poster'
      fullPath: '/bagikan-poster/'
      preLoaderRoute: typeof BagikanPosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pendaftaran/sukses': {
      id: '/pendaftaran/sukses'
      path: '/pendaftaran/sukses'
      fullPath: '/pendaftaran/sukses'
      preLoaderRoute: typeof PendaftaranSuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran/prestasi': {
      id: '/pendaftaran/prestasi'
      path: '/pendaftaran/prestasi'
      fullPath: '/pendaftaran/prestasi'
      preLoaderRoute: typeof PendaftaranPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran/ekonomi': {
      id: '/pendaftaran/ekonomi'
      path: '/pendaftaran/ekonomi'
      fullPath: '/pendaftaran/ekonomi'
      preLoaderRoute: typeof PendaftaranEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi/terima-kasih': {
      id: '/donasi/terima-kasih'
      path: '/donasi/terima-kasih'
      fullPath: '/donasi/terima-kasih'
      preLoaderRoute: typeof DonasiTerimaKasihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/terkirim': {
      id: '/berkas/terkirim'
      path: '/berkas/terkirim'
      fullPath: '/berkas/terkirim'
      preLoaderRoute: typeof BerkasTerkirimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/prestasi': {
      id: '/berkas/prestasi'
      path: '/berkas/prestasi'
      fullPath: '/berkas/prestasi'
      preLoaderRoute: typeof BerkasPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/ekonomi': {
      id: '/berkas/ekonomi'
      path: '/berkas/ekonomi'
      fullPath: '/berkas/ekonomi'
      preLoaderRoute: typeof BerkasEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagikan-poster/prestasi': {
      id: '/bagikan-poster/prestasi'
      path: '/bagikan-poster/prestasi'
      fullPath: '/bagikan-poster/prestasi'
      preLoaderRoute: typeof BagikanPosterPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagikan-poster/ekonomi': {
      id: '/bagikan-poster/ekonomi'
      path: '/bagikan-poster/ekonomi'
      fullPath: '/bagikan-poster/ekonomi'
      preLoaderRoute: typeof BagikanPosterEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sistem-update': {
      id: '/admin/sistem-update'
      path: '/sistem-update'
      fullPath: '/admin/sistem-update'
      preLoaderRoute: typeof AdminSistemUpdateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pendaftar': {
      id: '/admin/pendaftar'
      path: '/pendaftar'
      fullPath: '/admin/pendaftar'
      preLoaderRoute: typeof AdminPendaftarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kode-kustom': {
      id: '/admin/kode-kustom'
      path: '/kode-kustom'
      fullPath: '/admin/kode-kustom'
      preLoaderRoute: typeof AdminKodeKustomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keamanan': {
      id: '/admin/keamanan'
      path: '/keamanan'
      fullPath: '/admin/keamanan'
      preLoaderRoute: typeof AdminKeamananRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kandidat': {
      id: '/admin/kandidat'
      path: '/kandidat'
      fullPath: '/admin/kandidat'
      preLoaderRoute: typeof AdminKandidatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iklan-kustom': {
      id: '/admin/iklan-kustom'
      path: '/iklan-kustom'
      fullPath: '/admin/iklan-kustom'
      preLoaderRoute: typeof AdminIklanKustomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formulir': {
      id: '/admin/formulir'
      path: '/formulir'
      fullPath: '/admin/formulir'
      preLoaderRoute: typeof AdminFormulirRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-template': {
      id: '/admin/email-template'
      path: '/email-template'
      fullPath: '/admin/email-template'
      preLoaderRoute: typeof AdminEmailTemplateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donasi': {
      id: '/admin/donasi'
      path: '/donasi'
      fullPath: '/admin/donasi'
      preLoaderRoute: typeof AdminDonasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berkas': {
      id: '/admin/berkas'
      path: '/berkas'
      fullPath: '/admin/berkas'
      preLoaderRoute: typeof AdminBerkasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bagikan-poster': {
      id: '/admin/bagikan-poster'
      path: '/bagikan-poster'
      fullPath: '/admin/bagikan-poster'
      preLoaderRoute: typeof AdminBagikanPosterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artikel': {
      id: '/admin/artikel'
      path: '/artikel'
      fullPath: '/admin/artikel'
      preLoaderRoute: typeof AdminArtikelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-balasan': {
      id: '/admin/ai-balasan'
      path: '/ai-balasan'
      fullPath: '/admin/ai-balasan'
      preLoaderRoute: typeof AdminAiBalasanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adsense': {
      id: '/admin/adsense'
      path: '/adsense'
      fullPath: '/admin/adsense'
      preLoaderRoute: typeof AdminAdsenseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/berkas/prestasi/': {
      id: '/berkas/prestasi/'
      path: '/'
      fullPath: '/berkas/prestasi/'
      preLoaderRoute: typeof BerkasPrestasiIndexRouteImport
      parentRoute: typeof BerkasPrestasiRoute
    }
    '/berkas/ekonomi/': {
      id: '/berkas/ekonomi/'
      path: '/'
      fullPath: '/berkas/ekonomi/'
      preLoaderRoute: typeof BerkasEkonomiIndexRouteImport
      parentRoute: typeof BerkasEkonomiRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/prestasi/upload': {
      id: '/berkas/prestasi/upload'
      path: '/upload'
      fullPath: '/berkas/prestasi/upload'
      preLoaderRoute: typeof BerkasPrestasiUploadRouteImport
      parentRoute: typeof BerkasPrestasiRoute
    }
    '/berkas/ekonomi/upload': {
      id: '/berkas/ekonomi/upload'
      path: '/upload'
      fullPath: '/berkas/ekonomi/upload'
      preLoaderRoute: typeof BerkasEkonomiUploadRouteImport
      parentRoute: typeof BerkasEkonomiRoute
    }
    '/api/public/wa-webhook': {
      id: '/api/public/wa-webhook'
      path: '/api/public/wa-webhook'
      fullPath: '/api/public/wa-webhook'
      preLoaderRoute: typeof ApiPublicWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github-webhook': {
      id: '/api/public/github-webhook'
      path: '/api/public/github-webhook'
      fullPath: '/api/public/github-webhook'
      preLoaderRoute: typeof ApiPublicGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instalasi/vps': {
      id: '/admin/instalasi/vps'
      path: '/instalasi/vps'
      fullPath: '/admin/instalasi/vps'
      preLoaderRoute: typeof AdminInstalasiVpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instalasi/hosting': {
      id: '/admin/instalasi/hosting'
      path: '/instalasi/hosting'
      fullPath: '/admin/instalasi/hosting'
      preLoaderRoute: typeof AdminInstalasiHostingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdsenseRoute: typeof AdminAdsenseRoute
  AdminAiBalasanRoute: typeof AdminAiBalasanRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArtikelRoute: typeof AdminArtikelRoute
  AdminBagikanPosterRoute: typeof AdminBagikanPosterRoute
  AdminBerkasRoute: typeof AdminBerkasRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminDonasiRoute: typeof AdminDonasiRoute
  AdminEmailTemplateRoute: typeof AdminEmailTemplateRoute
  AdminFormulirRoute: typeof AdminFormulirRoute
  AdminIklanKustomRoute: typeof AdminIklanKustomRoute
  AdminKandidatRoute: typeof AdminKandidatRoute
  AdminKeamananRoute: typeof AdminKeamananRoute
  AdminKodeKustomRoute: typeof AdminKodeKustomRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPendaftarRoute: typeof AdminPendaftarRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminSistemUpdateRoute: typeof AdminSistemUpdateRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInstalasiHostingRoute: typeof AdminInstalasiHostingRoute
  AdminInstalasiVpsRoute: typeof AdminInstalasiVpsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsenseRoute: AdminAdsenseRoute,
  AdminAiBalasanRoute: AdminAiBalasanRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArtikelRoute: AdminArtikelRoute,
  AdminBagikanPosterRoute: AdminBagikanPosterRoute,
  AdminBerkasRoute: AdminBerkasRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminDonasiRoute: AdminDonasiRoute,
  AdminEmailTemplateRoute: AdminEmailTemplateRoute,
  AdminFormulirRoute: AdminFormulirRoute,
  AdminIklanKustomRoute: AdminIklanKustomRoute,
  AdminKandidatRoute: AdminKandidatRoute,
  AdminKeamananRoute: AdminKeamananRoute,
  AdminKodeKustomRoute: AdminKodeKustomRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPendaftarRoute: AdminPendaftarRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminSistemUpdateRoute: AdminSistemUpdateRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInstalasiHostingRoute: AdminInstalasiHostingRoute,
  AdminInstalasiVpsRoute: AdminInstalasiVpsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BerkasEkonomiRouteChildren {
  BerkasEkonomiUploadRoute: typeof BerkasEkonomiUploadRoute
  BerkasEkonomiIndexRoute: typeof BerkasEkonomiIndexRoute
}

const BerkasEkonomiRouteChildren: BerkasEkonomiRouteChildren = {
  BerkasEkonomiUploadRoute: BerkasEkonomiUploadRoute,
  BerkasEkonomiIndexRoute: BerkasEkonomiIndexRoute,
}

const BerkasEkonomiRouteWithChildren = BerkasEkonomiRoute._addFileChildren(
  BerkasEkonomiRouteChildren,
)

interface BerkasPrestasiRouteChildren {
  BerkasPrestasiUploadRoute: typeof BerkasPrestasiUploadRoute
  BerkasPrestasiIndexRoute: typeof BerkasPrestasiIndexRoute
}

const BerkasPrestasiRouteChildren: BerkasPrestasiRouteChildren = {
  BerkasPrestasiUploadRoute: BerkasPrestasiUploadRoute,
  BerkasPrestasiIndexRoute: BerkasPrestasiIndexRoute,
}

const BerkasPrestasiRouteWithChildren = BerkasPrestasiRoute._addFileChildren(
  BerkasPrestasiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsDottxtRoute: AdsDottxtRoute,
  BeasiswaEkonomiRoute: BeasiswaEkonomiRoute,
  BeasiswaPrestasiRoute: BeasiswaPrestasiRoute,
  CekStatusRoute: CekStatusRoute,
  DaftarRoute: DaftarRoute,
  LoginRoute: LoginRoute,
  TentangRoute: TentangRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  BagikanPosterEkonomiRoute: BagikanPosterEkonomiRoute,
  BagikanPosterPrestasiRoute: BagikanPosterPrestasiRoute,
  BerkasEkonomiRoute: BerkasEkonomiRouteWithChildren,
  BerkasPrestasiRoute: BerkasPrestasiRouteWithChildren,
  BerkasTerkirimRoute: BerkasTerkirimRoute,
  DonasiTerimaKasihRoute: DonasiTerimaKasihRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PendaftaranEkonomiRoute: PendaftaranEkonomiRoute,
  PendaftaranPrestasiRoute: PendaftaranPrestasiRoute,
  PendaftaranSuksesRoute: PendaftaranSuksesRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
  BagikanPosterIndexRoute: BagikanPosterIndexRoute,
  BerkasIndexRoute: BerkasIndexRoute,
  ApiPublicGithubWebhookRoute: ApiPublicGithubWebhookRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicWaWebhookRoute: ApiPublicWaWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
