/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as BeasiswaPrestasiRouteImport } from './routes/beasiswa-prestasi'
import { Route as BeasiswaEkonomiRouteImport } from './routes/beasiswa-ekonomi'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BerkasIndexRouteImport } from './routes/berkas.index'
import { Route as BagikanPosterIndexRouteImport } from './routes/bagikan-poster.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PendaftaranPrestasiRouteImport } from './routes/pendaftaran.prestasi'
import { Route as PendaftaranEkonomiRouteImport } from './routes/pendaftaran.ekonomi'
import { Route as BerkasPrestasiRouteImport } from './routes/berkas.prestasi'
import { Route as BerkasEkonomiRouteImport } from './routes/berkas.ekonomi'
import { Route as BagikanPosterPrestasiRouteImport } from './routes/bagikan-poster.prestasi'
import { Route as BagikanPosterEkonomiRouteImport } from './routes/bagikan-poster.ekonomi'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminPendaftarRouteImport } from './routes/admin.pendaftar'
import { Route as AdminAdsenseRouteImport } from './routes/admin.adsense'
import { Route as BerkasPrestasiUploadRouteImport } from './routes/berkas.prestasi.upload'
import { Route as BerkasEkonomiUploadRouteImport } from './routes/berkas.ekonomi.upload'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const BeasiswaPrestasiRoute = BeasiswaPrestasiRouteImport.update({
  id: '/beasiswa-prestasi',
  path: '/beasiswa-prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BeasiswaEkonomiRoute = BeasiswaEkonomiRouteImport.update({
  id: '/beasiswa-ekonomi',
  path: '/beasiswa-ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasIndexRoute = BerkasIndexRouteImport.update({
  id: '/berkas/',
  path: '/berkas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagikanPosterIndexRoute = BagikanPosterIndexRouteImport.update({
  id: '/bagikan-poster/',
  path: '/bagikan-poster/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PendaftaranPrestasiRoute = PendaftaranPrestasiRouteImport.update({
  id: '/pendaftaran/prestasi',
  path: '/pendaftaran/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranEkonomiRoute = PendaftaranEkonomiRouteImport.update({
  id: '/pendaftaran/ekonomi',
  path: '/pendaftaran/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasPrestasiRoute = BerkasPrestasiRouteImport.update({
  id: '/berkas/prestasi',
  path: '/berkas/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasEkonomiRoute = BerkasEkonomiRouteImport.update({
  id: '/berkas/ekonomi',
  path: '/berkas/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const BagikanPosterPrestasiRoute = BagikanPosterPrestasiRouteImport.update({
  id: '/bagikan-poster/prestasi',
  path: '/bagikan-poster/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BagikanPosterEkonomiRoute = BagikanPosterEkonomiRouteImport.update({
  id: '/bagikan-poster/ekonomi',
  path: '/bagikan-poster/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendaftarRoute = AdminPendaftarRouteImport.update({
  id: '/pendaftar',
  path: '/pendaftar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsenseRoute = AdminAdsenseRouteImport.update({
  id: '/adsense',
  path: '/adsense',
  getParentRoute: () => AdminRoute,
} as any)
const BerkasPrestasiUploadRoute = BerkasPrestasiUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => BerkasPrestasiRoute,
} as any)
const BerkasEkonomiUploadRoute = BerkasEkonomiUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => BerkasEkonomiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads.txt': typeof AdsDottxtRoute
  '/artikel': typeof ArtikelRoute
  '/beasiswa-ekonomi': typeof BeasiswaEkonomiRoute
  '/beasiswa-prestasi': typeof BeasiswaPrestasiRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/admin/adsense': typeof AdminAdsenseRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/bagikan-poster/ekonomi': typeof BagikanPosterEkonomiRoute
  '/bagikan-poster/prestasi': typeof BagikanPosterPrestasiRoute
  '/berkas/ekonomi': typeof BerkasEkonomiRouteWithChildren
  '/berkas/prestasi': typeof BerkasPrestasiRouteWithChildren
  '/pendaftaran/ekonomi': typeof PendaftaranEkonomiRoute
  '/pendaftaran/prestasi': typeof PendaftaranPrestasiRoute
  '/admin/': typeof AdminIndexRoute
  '/bagikan-poster/': typeof BagikanPosterIndexRoute
  '/berkas/': typeof BerkasIndexRoute
  '/berkas/ekonomi/upload': typeof BerkasEkonomiUploadRoute
  '/berkas/prestasi/upload': typeof BerkasPrestasiUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/artikel': typeof ArtikelRoute
  '/beasiswa-ekonomi': typeof BeasiswaEkonomiRoute
  '/beasiswa-prestasi': typeof BeasiswaPrestasiRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/admin/adsense': typeof AdminAdsenseRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/bagikan-poster/ekonomi': typeof BagikanPosterEkonomiRoute
  '/bagikan-poster/prestasi': typeof BagikanPosterPrestasiRoute
  '/berkas/ekonomi': typeof BerkasEkonomiRouteWithChildren
  '/berkas/prestasi': typeof BerkasPrestasiRouteWithChildren
  '/pendaftaran/ekonomi': typeof PendaftaranEkonomiRoute
  '/pendaftaran/prestasi': typeof PendaftaranPrestasiRoute
  '/admin': typeof AdminIndexRoute
  '/bagikan-poster': typeof BagikanPosterIndexRoute
  '/berkas': typeof BerkasIndexRoute
  '/berkas/ekonomi/upload': typeof BerkasEkonomiUploadRoute
  '/berkas/prestasi/upload': typeof BerkasPrestasiUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads.txt': typeof AdsDottxtRoute
  '/artikel': typeof ArtikelRoute
  '/beasiswa-ekonomi': typeof BeasiswaEkonomiRoute
  '/beasiswa-prestasi': typeof BeasiswaPrestasiRoute
  '/daftar': typeof DaftarRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/admin/adsense': typeof AdminAdsenseRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/bagikan-poster/ekonomi': typeof BagikanPosterEkonomiRoute
  '/bagikan-poster/prestasi': typeof BagikanPosterPrestasiRoute
  '/berkas/ekonomi': typeof BerkasEkonomiRouteWithChildren
  '/berkas/prestasi': typeof BerkasPrestasiRouteWithChildren
  '/pendaftaran/ekonomi': typeof PendaftaranEkonomiRoute
  '/pendaftaran/prestasi': typeof PendaftaranPrestasiRoute
  '/admin/': typeof AdminIndexRoute
  '/bagikan-poster/': typeof BagikanPosterIndexRoute
  '/berkas/': typeof BerkasIndexRoute
  '/berkas/ekonomi/upload': typeof BerkasEkonomiUploadRoute
  '/berkas/prestasi/upload': typeof BerkasPrestasiUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ads.txt'
    | '/artikel'
    | '/beasiswa-ekonomi'
    | '/beasiswa-prestasi'
    | '/daftar'
    | '/login'
    | '/tentang'
    | '/admin/adsense'
    | '/admin/pendaftar'
    | '/admin/pengaturan'
    | '/bagikan-poster/ekonomi'
    | '/bagikan-poster/prestasi'
    | '/berkas/ekonomi'
    | '/berkas/prestasi'
    | '/pendaftaran/ekonomi'
    | '/pendaftaran/prestasi'
    | '/admin/'
    | '/bagikan-poster/'
    | '/berkas/'
    | '/berkas/ekonomi/upload'
    | '/berkas/prestasi/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads.txt'
    | '/artikel'
    | '/beasiswa-ekonomi'
    | '/beasiswa-prestasi'
    | '/daftar'
    | '/login'
    | '/tentang'
    | '/admin/adsense'
    | '/admin/pendaftar'
    | '/admin/pengaturan'
    | '/bagikan-poster/ekonomi'
    | '/bagikan-poster/prestasi'
    | '/berkas/ekonomi'
    | '/berkas/prestasi'
    | '/pendaftaran/ekonomi'
    | '/pendaftaran/prestasi'
    | '/admin'
    | '/bagikan-poster'
    | '/berkas'
    | '/berkas/ekonomi/upload'
    | '/berkas/prestasi/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ads.txt'
    | '/artikel'
    | '/beasiswa-ekonomi'
    | '/beasiswa-prestasi'
    | '/daftar'
    | '/login'
    | '/tentang'
    | '/admin/adsense'
    | '/admin/pendaftar'
    | '/admin/pengaturan'
    | '/bagikan-poster/ekonomi'
    | '/bagikan-poster/prestasi'
    | '/berkas/ekonomi'
    | '/berkas/prestasi'
    | '/pendaftaran/ekonomi'
    | '/pendaftaran/prestasi'
    | '/admin/'
    | '/bagikan-poster/'
    | '/berkas/'
    | '/berkas/ekonomi/upload'
    | '/berkas/prestasi/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdsDottxtRoute: typeof AdsDottxtRoute
  ArtikelRoute: typeof ArtikelRoute
  BeasiswaEkonomiRoute: typeof BeasiswaEkonomiRoute
  BeasiswaPrestasiRoute: typeof BeasiswaPrestasiRoute
  DaftarRoute: typeof DaftarRoute
  LoginRoute: typeof LoginRoute
  TentangRoute: typeof TentangRoute
  BagikanPosterEkonomiRoute: typeof BagikanPosterEkonomiRoute
  BagikanPosterPrestasiRoute: typeof BagikanPosterPrestasiRoute
  BerkasEkonomiRoute: typeof BerkasEkonomiRouteWithChildren
  BerkasPrestasiRoute: typeof BerkasPrestasiRouteWithChildren
  PendaftaranEkonomiRoute: typeof PendaftaranEkonomiRoute
  PendaftaranPrestasiRoute: typeof PendaftaranPrestasiRoute
  BagikanPosterIndexRoute: typeof BagikanPosterIndexRoute
  BerkasIndexRoute: typeof BerkasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beasiswa-prestasi': {
      id: '/beasiswa-prestasi'
      path: '/beasiswa-prestasi'
      fullPath: '/beasiswa-prestasi'
      preLoaderRoute: typeof BeasiswaPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beasiswa-ekonomi': {
      id: '/beasiswa-ekonomi'
      path: '/beasiswa-ekonomi'
      fullPath: '/beasiswa-ekonomi'
      preLoaderRoute: typeof BeasiswaEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/': {
      id: '/berkas/'
      path: '/berkas'
      fullPath: '/berkas/'
      preLoaderRoute: typeof BerkasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagikan-poster/': {
      id: '/bagikan-poster/'
      path: '/bagikan-poster'
      fullPath: '/bagikan-poster/'
      preLoaderRoute: typeof BagikanPosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pendaftaran/prestasi': {
      id: '/pendaftaran/prestasi'
      path: '/pendaftaran/prestasi'
      fullPath: '/pendaftaran/prestasi'
      preLoaderRoute: typeof PendaftaranPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran/ekonomi': {
      id: '/pendaftaran/ekonomi'
      path: '/pendaftaran/ekonomi'
      fullPath: '/pendaftaran/ekonomi'
      preLoaderRoute: typeof PendaftaranEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/prestasi': {
      id: '/berkas/prestasi'
      path: '/berkas/prestasi'
      fullPath: '/berkas/prestasi'
      preLoaderRoute: typeof BerkasPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/ekonomi': {
      id: '/berkas/ekonomi'
      path: '/berkas/ekonomi'
      fullPath: '/berkas/ekonomi'
      preLoaderRoute: typeof BerkasEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagikan-poster/prestasi': {
      id: '/bagikan-poster/prestasi'
      path: '/bagikan-poster/prestasi'
      fullPath: '/bagikan-poster/prestasi'
      preLoaderRoute: typeof BagikanPosterPrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagikan-poster/ekonomi': {
      id: '/bagikan-poster/ekonomi'
      path: '/bagikan-poster/ekonomi'
      fullPath: '/bagikan-poster/ekonomi'
      preLoaderRoute: typeof BagikanPosterEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pendaftar': {
      id: '/admin/pendaftar'
      path: '/pendaftar'
      fullPath: '/admin/pendaftar'
      preLoaderRoute: typeof AdminPendaftarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adsense': {
      id: '/admin/adsense'
      path: '/adsense'
      fullPath: '/admin/adsense'
      preLoaderRoute: typeof AdminAdsenseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/berkas/prestasi/upload': {
      id: '/berkas/prestasi/upload'
      path: '/upload'
      fullPath: '/berkas/prestasi/upload'
      preLoaderRoute: typeof BerkasPrestasiUploadRouteImport
      parentRoute: typeof BerkasPrestasiRoute
    }
    '/berkas/ekonomi/upload': {
      id: '/berkas/ekonomi/upload'
      path: '/upload'
      fullPath: '/berkas/ekonomi/upload'
      preLoaderRoute: typeof BerkasEkonomiUploadRouteImport
      parentRoute: typeof BerkasEkonomiRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsenseRoute: typeof AdminAdsenseRoute
  AdminPendaftarRoute: typeof AdminPendaftarRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsenseRoute: AdminAdsenseRoute,
  AdminPendaftarRoute: AdminPendaftarRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BerkasEkonomiRouteChildren {
  BerkasEkonomiUploadRoute: typeof BerkasEkonomiUploadRoute
}

const BerkasEkonomiRouteChildren: BerkasEkonomiRouteChildren = {
  BerkasEkonomiUploadRoute: BerkasEkonomiUploadRoute,
}

const BerkasEkonomiRouteWithChildren = BerkasEkonomiRoute._addFileChildren(
  BerkasEkonomiRouteChildren,
)

interface BerkasPrestasiRouteChildren {
  BerkasPrestasiUploadRoute: typeof BerkasPrestasiUploadRoute
}

const BerkasPrestasiRouteChildren: BerkasPrestasiRouteChildren = {
  BerkasPrestasiUploadRoute: BerkasPrestasiUploadRoute,
}

const BerkasPrestasiRouteWithChildren = BerkasPrestasiRoute._addFileChildren(
  BerkasPrestasiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsDottxtRoute: AdsDottxtRoute,
  ArtikelRoute: ArtikelRoute,
  BeasiswaEkonomiRoute: BeasiswaEkonomiRoute,
  BeasiswaPrestasiRoute: BeasiswaPrestasiRoute,
  DaftarRoute: DaftarRoute,
  LoginRoute: LoginRoute,
  TentangRoute: TentangRoute,
  BagikanPosterEkonomiRoute: BagikanPosterEkonomiRoute,
  BagikanPosterPrestasiRoute: BagikanPosterPrestasiRoute,
  BerkasEkonomiRoute: BerkasEkonomiRouteWithChildren,
  BerkasPrestasiRoute: BerkasPrestasiRouteWithChildren,
  PendaftaranEkonomiRoute: PendaftaranEkonomiRoute,
  PendaftaranPrestasiRoute: PendaftaranPrestasiRoute,
  BagikanPosterIndexRoute: BagikanPosterIndexRoute,
  BerkasIndexRoute: BerkasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
