
UPDATE public.ai_knowledge_base
SET answer = E'Cara daftar Beasiswa Kejar Prestasi sangat mudah kak:\n1. Buka website resmi di www.kejarprestasi.id\n2. Pilih jalur beasiswa: Prestasi atau Ekonomi\n3. Klik tombol Daftar Sekarang pada jalur yang dipilih\n4. Isi formulir pendaftaran dengan data diri yang benar (nama lengkap, tempat & tanggal lahir, alamat, WhatsApp aktif, email aktif, asal sekolah/kampus, dll)\n5. Periksa kembali data sebelum klik Kirim Pendaftaran\n6. Setelah berhasil, kakak akan mendapatkan Kode Token via halaman sukses, email, dan WhatsApp\n7. Simpan Kode Token tersebut, lalu lanjut ke tahap Kirim Berkas\n\nSemua proses dilakukan online melalui www.kejarprestasi.id ya kak. Gratis, tidak dipungut biaya apapun. 🙏'
WHERE id = '44676f52-71be-4478-8ea4-7049897ca701';

UPDATE public.ai_knowledge_base
SET answer = E'Cara kirim berkas Beasiswa Kejar Prestasi:\n1. Pastikan kakak sudah menyelesaikan pendaftaran dan menerima Kode Token\n2. Buka www.kejarprestasi.id lalu pilih menu Kirim Berkas\n3. Pilih jalur sesuai pendaftaran (Prestasi atau Ekonomi)\n4. Baca daftar berkas yang perlu disiapkan, lalu klik Lanjut ke Unggah Berkas\n5. Masukkan email yang sama dengan saat pendaftaran\n6. Unggah seluruh berkas yang diminta sesuai jalur kakak\n7. Klik Kirim Berkas dan tunggu konfirmasi via email/WhatsApp\n\nFormat file yang diterima: PDF, JPG, PNG, MP4. Pastikan dokumen jelas terbaca ya kak. 🙏'
WHERE id = 'dec5299e-e4b6-452a-aad5-4fe5de077b6c';

INSERT INTO public.ai_knowledge_base (question, answer, category, sort_order) VALUES
('Langkah-langkah daftar Beasiswa Prestasi', E'Berikut langkah daftar Beasiswa Prestasi kak:\n1. Buka www.kejarprestasi.id\n2. Pilih menu Beasiswa Prestasi atau klik Daftar Sekarang pada kartu Prestasi\n3. Klik tombol Daftar Beasiswa Prestasi\n4. Isi formulir pendaftaran (data diri, kontak, asal sekolah/kampus, dll)\n5. Klik Kirim Pendaftaran\n6. Simpan Kode Token yang muncul di halaman sukses (juga dikirim via email & WhatsApp)\n7. Lanjutkan ke Kirim Berkas Prestasi di www.kejarprestasi.id\n\nPendaftaran 100% gratis ya kak. 🙏', 'Pendaftaran', 10),
('Langkah-langkah daftar Beasiswa Ekonomi', E'Berikut langkah daftar Beasiswa Ekonomi kak:\n1. Buka www.kejarprestasi.id\n2. Pilih menu Beasiswa Ekonomi atau klik Daftar Sekarang pada kartu Ekonomi\n3. Klik tombol Daftar Beasiswa Ekonomi\n4. Isi formulir pendaftaran dengan jujur dan lengkap\n5. Klik Kirim Pendaftaran\n6. Simpan Kode Token (dikirim juga via email & WhatsApp)\n7. Lanjut ke Kirim Berkas Ekonomi di www.kejarprestasi.id\n\nTidak dipungut biaya sepeser pun ya kak. 🙏', 'Pendaftaran', 11),
('Langkah-langkah kirim berkas Prestasi', E'Cara kirim berkas Prestasi kak:\n1. Buka www.kejarprestasi.id, pilih Kirim Berkas lalu Prestasi\n2. Baca daftar berkas yang perlu disiapkan (Kartu Pelajar/Mahasiswa, Rapor/Transkrip, Sertifikat Prestasi, Essay Motivasi, dll)\n3. Klik Lanjut ke Unggah Berkas\n4. Masukkan email yang sama saat pendaftaran agar berkas terhubung dengan akun kakak\n5. Unggah satu per satu berkas sesuai slot\n6. Klik Kirim Berkas\n7. Tunggu konfirmasi verifikasi via email & WhatsApp\n\nFormat file: PDF, JPG, PNG, MP4. Pastikan dokumen jelas dan tidak terpotong ya kak. 🙏', 'Berkas', 12),
('Langkah-langkah kirim berkas Ekonomi', E'Cara kirim berkas Ekonomi kak:\n1. Buka www.kejarprestasi.id, pilih Kirim Berkas lalu Ekonomi\n2. Siapkan berkas: Kartu Pelajar/Mahasiswa, Surat Keterangan Penghasilan Orang Tua, Surat Tidak Mampu (opsional), Rapor/Transkrip, Video Motivasi (opsional)\n3. Klik Lanjut ke Unggah Berkas\n4. Masukkan email yang sama saat pendaftaran\n5. Unggah seluruh berkas yang diminta\n6. Klik Kirim Berkas\n7. Tunggu konfirmasi verifikasi via email & WhatsApp\n\nFormat file: PDF, JPG, PNG, MP4. 🙏', 'Berkas', 13),
('Alur lengkap pendaftaran Beasiswa Kejar Prestasi', E'Alur lengkap mengikuti Beasiswa Kejar Prestasi kak:\n1. Daftar di www.kejarprestasi.id (pilih jalur Prestasi atau Ekonomi)\n2. Terima Kode Token (lewat halaman sukses, email, dan WhatsApp)\n3. Kirim Berkas via menu Kirim Berkas di www.kejarprestasi.id\n4. Bagikan Poster Kejar Prestasi (langkah penting untuk lolos administrasi)\n5. Cek Status pendaftaran di menu Cek Status — masukkan Kode Token / email\n6. Mengikuti tahap seleksi (TPA & wawancara) sesuai jadwal\n7. Pengumuman finalis & Awarding\n\nSemua tahap dilakukan melalui www.kejarprestasi.id ya kak. 🙏', 'Pendaftaran', 14),
('Saya sudah daftar, selanjutnya apa?', E'Setelah pendaftaran berhasil, langkah berikutnya kak:\n1. Simpan Kode Token kakak baik-baik\n2. Buka www.kejarprestasi.id lalu menu Kirim Berkas, pilih jalur kakak\n3. Unggah seluruh berkas yang diminta menggunakan email yang sama saat daftar\n4. Lanjutkan ke menu Bagikan Poster\n5. Pantau status pendaftaran melalui menu Cek Status\n\nKalau ada kendala, kakak bisa hubungi admin via WhatsApp resmi ya. 🙏', 'Pendaftaran', 15),
('Di mana saya mendaftar Beasiswa Kejar Prestasi?', 'Pendaftaran Beasiswa Kejar Prestasi hanya dilakukan secara online melalui website resmi di www.kejarprestasi.id ya kak. Hati-hati terhadap link/website lain yang mengatasnamakan Kejar Prestasi. 🙏', 'Pendaftaran', 16),
('Apakah ada aplikasi untuk mendaftar?', 'Saat ini pendaftaran cukup melalui website resmi www.kejarprestasi.id kak, tanpa perlu aplikasi tambahan. Bisa diakses langsung dari HP maupun laptop. 🙏', 'Pendaftaran', 17),
('Link pendaftaran beasiswa', E'Link resmi pendaftaran Beasiswa Kejar Prestasi: www.kejarprestasi.id\n\nPilih menu Beasiswa Prestasi atau Beasiswa Ekonomi, lalu klik Daftar Sekarang ya kak. 🙏', 'Pendaftaran', 18),
('Link kirim/unggah berkas', 'Pengiriman berkas dilakukan di www.kejarprestasi.id pada menu Kirim Berkas, pilih jalur Prestasi atau Ekonomi sesuai pendaftaran kakak. 🙏', 'Berkas', 19);

UPDATE public.ai_behavior
SET system_prompt = E'Anda adalah asisten resmi Beasiswa Kejar Prestasi. Jawab pertanyaan calon pendaftar dengan ramah, jelas, singkat, dan profesional menggunakan Bahasa Indonesia yang baik. Sapa pengguna dengan panggilan kak/kakak agar lebih akrab.\n\nAturan format jawaban:\n- Tulis dalam teks biasa (plain text). Dilarang menggunakan markdown: tanpa **, *, _, `, #, atau daftar bullet markdown.\n- Jangan menyebutkan batas/maksimal ukuran file (misal MB) dalam jawaban. Cukup sebutkan format yang diterima (PDF, JPG, PNG, MP4).\n- Untuk semua pertanyaan terkait pendaftaran, kirim berkas, cek status, atau bagikan poster, arahkan pengguna ke website resmi www.kejarprestasi.id.\n\nAturan keamanan (WAJIB):\n- DILARANG menyebut, membocorkan, atau merujuk halaman/dashboard admin internal (contoh: /admin, /login admin, panel admin, dashboard admin, kode-kustom, ai-balasan, pengaturan internal, dsb).\n- DILARANG membagikan URL internal, endpoint API, webhook, token rahasia, struktur database, atau informasi teknis backend kepada pengguna.\n- Jika pengguna bertanya tentang admin/dashboard/sistem internal, jawab sopan bahwa informasi tersebut tidak dapat dibagikan dan arahkan ke www.kejarprestasi.id atau hubungi admin via WhatsApp resmi.\n\nJika informasi tidak tersedia di basis pengetahuan, sampaikan dengan sopan dan arahkan pengguna ke www.kejarprestasi.id atau menghubungi admin via WhatsApp resmi.'
WHERE id IS NOT NULL;
